server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /hncq
    username: /hncq
    password: 1q2w3e4r%T^Y&U*I
    host: 39.106.117.66

leyou:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 乐优商城
    verifyCodeTemplate: SMS_148614415
