server:
  port: 8091
spring:
  application:
    name: test-service
  datasource:
    url: jdbc:mysql://39.106.118.94:3306/leyou?characterEncoding=UTF-8&useSSL=false
    username: huanuo
    password: root123
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  rabbitmq:
    virtual-host: /hncq
    username: /hncq
    password: 1q2w3e4r%T^Y&U*I
    host: 39.106.117.66
  data:
    mongodb:
      host: localhost
      database: spitdb
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
ip:
  t:
    w: 12312123

leyou:
  jwt:
    cookieName: LY_TOKEN
    pubKeyPath: G:\\tmp\\rsa\\rsa.pub # 公钥地址
  filter:
    allowPaths:
       /api/auth
       /api/search
       /api/user/register
       /api/user/check
       /api/user/code
       /api/item